FROM node:20-alpine AS builder

RUN corepack enable
WORKDIR /app

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn ./.yarn 
COPY tsconfig*.json ./
COPY nest-cli.json ./
COPY prisma ./prisma/

RUN yarn install --immutable

COPY . .

RUN yarn prisma generate
RUN yarn build


FROM node:20-alpine

RUN corepack enable
WORKDIR /app


COPY --from=builder /app/package.json /app/yarn.lock /app/.yarnrc.yml ./
COPY --from=builder /app/.yarn ./.yarn
COPY --from=builder /app/prisma ./prisma
COPY --from=builder /app/dist ./dist

RUN yarn workspaces focus --production

COPY --from=builder /app/node_modules/.prisma ./node_modules/.prisma
COPY --from=builder /app/node_modules/@prisma/client ./node_modules/@prisma/client
COPY --from=builder /app/node_modules/prisma ./node_modules/prisma

EXPOSE 3000

CMD ["yarn", "run", "start:prod"]